name: storybook-release
on: 
  push:
    branches: 
      - dev
    tags:
      - 'w-v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Install Chat Widget packages
        working-directory: chat-widget
        run: yarn install
      - name: Build Composite Storybook
        working-directory: chat-widget
        run: yarn build-composite-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          BRANCH: gh-pages
          FOLDER: ./chat-widget/storybook-build
          TARGET_FOLDER: omnichannel-chat-widget/storybook